# Generated by Django 5.2.11 on 2026-02-21 14:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UltraShop', max_length=200)),
                ('support_email', models.EmailField(default='support@ultra-shop.com', max_length=254)),
                ('terms_url', models.URLField(blank=True, default='')),
                ('privacy_url', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('default_timezone', models.CharField(default='Asia/Tehran', max_length=50)),
                ('default_currency', models.CharField(default='IRR', max_length=10)),
                ('default_guest_checkout', models.BooleanField(default=True)),
                ('reserved_usernames', models.JSONField(blank=True, default=list, help_text='JSON array of reserved subdomain names')),
                ('sms_provider', models.CharField(blank=True, default='', max_length=50)),
                ('sms_api_key_encrypted', models.TextField(blank=True, default='')),
                ('sms_sender', models.CharField(blank=True, default='', max_length=30)),
                ('email_host', models.CharField(blank=True, default='', max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_username', models.CharField(blank=True, default='', max_length=200)),
                ('email_password_encrypted', models.TextField(blank=True, default='')),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_from', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.SlugField(help_text='Subdomain: username.ultra-shop.com', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='stores/favicons/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('theme_preset', models.CharField(default='minimal', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('type', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom Domain')], max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('ssl_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active')], default='none', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.store')),
            ],
            options={
                'db_table': 'store_domains',
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_staff',
                'unique_together': {('store', 'user')},
            },
        ),
    ]
