# Generated by Django 5.2.11 on 2026-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UltraShop', max_length=255, verbose_name='Platform name')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Support email')),
                ('terms_url', models.URLField(blank=True, verbose_name='Terms of service URL')),
                ('privacy_url', models.URLField(blank=True, verbose_name='Privacy policy URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='platform/', verbose_name='Favicon')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
