# Generated by Django 5.2.11 on 2026-02-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tokens', models.JSONField(default=dict, help_text='Token values for this preset')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='theme_presets/')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('deprecated', 'منسوخ'), ('draft', 'پیشنویس')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'theme_presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7)),
                ('heading_font', models.CharField(default='Vazirmatn', help_text='فونت تیترها', max_length=100)),
                ('body_font', models.CharField(default='Vazirmatn', help_text='فونت متن', max_length=100)),
                ('radius_scale', models.CharField(choices=[('none', 'بدون گردی'), ('sm', 'کم'), ('md', 'متوسط'), ('lg', 'زیاد'), ('xl', 'خیلی زیاد'), ('full', 'کامل')], default='md', max_length=10)),
                ('shadow_level', models.CharField(choices=[('none', 'بدون سایه'), ('sm', 'سبک'), ('md', 'متوسط'), ('lg', 'سنگین'), ('xl', 'خیلی سنگین')], default='md', max_length=10)),
                ('custom_css', models.TextField(blank=True, default='', help_text='CSS سفارشی (حداکثر ۵۰ کیلوبایت)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='core.store')),
                ('theme_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='core.themepreset')),
            ],
            options={
                'db_table': 'store_themes',
            },
        ),
    ]
