# Generated by Django 5.0 on 2026-02-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_themepreset_storetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'صفحه اصلی'), ('category', 'صفحه دسته\u200cبندی'), ('product', 'صفحه محصول'), ('custom', 'صفحه سفارشی')], default='home', max_length=20)),
                ('block_order', models.JSONField(default=list, help_text="Ordered list of block IDs, e.g. ['hero', 'product_grid', 'category_grid']")),
                ('block_settings', models.JSONField(default=dict, help_text='Per-block settings: { block_id: { ... } }')),
                ('block_enabled', models.JSONField(default=dict, help_text='Per-block enabled: { block_id: true/false }')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_configs', to='core.store')),
            ],
            options={
                'db_table': 'layout_configurations',
                'ordering': ['store', 'page_type'],
                'unique_together': {('store', 'page_type')},
            },
        ),
        migrations.CreateModel(
            name='LayoutConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('block_order', models.JSONField(default=list)),
                ('block_settings', models.JSONField(default=dict)),
                ('block_enabled', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_snapshots', to='core.store')),
            ],
            options={
                'db_table': 'layout_configuration_snapshots',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'page_type', 'version')},
            },
        ),
    ]
