# Generated by Django 5.0 on 2026-02-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_layout_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='First warehouse for this store; used when no warehouse is specified.')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower = higher priority for routing (e.g. nearest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.store')),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='storestaff',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Empty = access to all warehouses; otherwise only listed warehouses.', related_name='staff_members', to='core.warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['store', 'is_active'], name='warehouses_store_i_23c7ff_idx'),
        ),
    ]
