# Generated by Django 5.0 on 2026-02-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_default_warehouse_per_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='anthropic_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='image_gen_model',
            field=models.CharField(default='flux', max_length=80),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='openai_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='rate_limit_per_store_daily',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='text_model',
            field=models.CharField(default='gpt-4o-mini', max_length=80),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='vision_model',
            field=models.CharField(default='gpt-4o', max_length=80),
        ),
        migrations.CreateModel(
            name='AIDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_usage', to='core.store')),
            ],
            options={
                'db_table': 'ai_daily_usage',
                'ordering': ['-date'],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
