# Generated by Django 5.0 on 2026-02-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ai_config_and_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short slogan (SO-07)', max_length=300),
        ),
    ]
