# Generated by Django 5.2.11 on 2026-04-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_store_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('max_warehouses', models.PositiveIntegerField(default=1)),
                ('max_products', models.PositiveIntegerField(default=100)),
                ('max_ai_requests_daily', models.PositiveIntegerField(default=10)),
                ('allow_custom_domain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_plans',
            },
        ),
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('sales_agent', 'مسئول فروش'), ('accountant', 'حسابدار')], default='staff', max_length=15),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storeplan'),
        ),
    ]
