# Generated by Django 5.2.11 on 2026-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storeplan_alter_storestaff_role_store_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestaff',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('sales_agent', 'مسئول فروش'), ('accountant', 'حسابدار')], default='staff', max_length=20),
        ),
    ]
