# Generated by Django 5.2.11 on 2026-04-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_storestaff_role_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(db_index=True, max_length=50)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.store')),
            ],
            options={
                'db_table': 'store_integrations',
                'ordering': ['integration_id'],
                'unique_together': {('store', 'integration_id')},
            },
        ),
    ]
