# Generated by Django 5.2.11 on 2026-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_store_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_from',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='email_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='store',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('kavenegar', 'کاوه نگار'), ('smsir', 'sms.ir')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='sms_sender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
