# Generated by Django 5.2.11 on 2026-04-11 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_store_auto_route_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=300)),
                ('caption', models.TextField(blank=True, default='')),
                ('hashtags', models.CharField(blank=True, default='', max_length=500)),
                ('suggested_time', models.CharField(blank=True, default='', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='core.store')),
            ],
            options={
                'db_table': 'content_calendar_entries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CROSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('impact', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('dismissed', 'رد شد')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cro_suggestions', to='core.store')),
            ],
            options={
                'db_table': 'cro_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
