# Generated by Django 5.2.11 on 2026-04-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_so18_content_calendar_so47_cro_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='generated_logo_url',
            field=models.URLField(blank=True, default='', help_text='آدرس لوگوی تولیدشده توسط AI (SO-07)'),
        ),
    ]
