# Generated by Django 5.2.11 on 2026-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_store_generated_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='openai_base_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
