# Generated by Django 5.2.11 on 2026-04-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_platformsettings_openai_base_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentCalendarEntry',
        ),
    ]
