# Generated by Django 5.2.11 on 2026-04-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_storestaff_role_max_length'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cart_data', models.JSONField(default=dict, help_text='{str(variant_pk): quantity}')),
                ('recovered', models.BooleanField(default=False)),
                ('recovery_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to='core.store')),
            ],
            options={
                'db_table': 'abandoned_carts',
                'indexes': [models.Index(fields=['store', 'recovered', 'updated_at'], name='abandoned_c_store_i_367a9a_idx')],
            },
        ),
    ]
