# Generated by Django 5.2.11 on 2026-04-10 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_storeplan_alter_storestaff_role_store_plan'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(blank=True, default='', help_text='contact_form, chat, manual', max_length=50)),
                ('stage', models.CharField(choices=[('new', 'سرنخ جدید'), ('contacted', 'تماس گرفته شد'), ('negotiation', 'در حال مذاکره'), ('won', 'موفق'), ('lost', 'ناموفق')], default='new', max_length=15)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.store')),
            ],
            options={
                'db_table': 'crm_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('order', 'سفارش'), ('note', 'یادداشت'), ('call', 'تماس'), ('email', 'ایمیل'), ('chat', 'چت')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_id', models.CharField(blank=True, default='', help_text='e.g. order pk', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_activities', to='core.store')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_contact_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_tasks', to='core.store')),
            ],
            options={
                'db_table': 'crm_sale_tasks',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
