# Generated by Django 5.0 on 2026-02-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0004_warehouse_and_staff_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Legacy: total stock. Prefer total_stock (sum of warehouse_stocks) when using multi-warehouse.'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Quantity reserved for orders (e.g. pending shipment).')),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lines', to='core.warehouse')),
            ],
            options={
                'db_table': 'warehouse_stocks',
                'indexes': [models.Index(fields=['warehouse'], name='warehouse_s_warehou_cb922c_idx'), models.Index(fields=['variant'], name='warehouse_s_variant_c1d317_idx')],
                'unique_together': {('warehouse', 'variant')},
            },
        ),
    ]
