# Generated by Django 5.0 on 2026-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_populate_warehouse_stock_from_variant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='focus_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords for SEO (SO-17)', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, default='', help_text='Open Graph description for social share (SO-17)'),
        ),
    ]
