# Generated by Django 5.2.11 on 2026-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='آیا این محصول نیاز به ارسال فیزیکی دارد؟'),
        ),
    ]
