# Generated by Django 5.2.11 on 2026-04-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_requires_shipping'),
        ('core', '0009_alter_storestaff_role_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('percent', 'درصد'), ('fixed', 'مبلغ ثابت')], max_length=10)),
                ('value', models.PositiveBigIntegerField(help_text='درصد (۰-۱۰۰) یا مبلغ ثابت به ریال')),
                ('min_order_amount', models.PositiveBigIntegerField(default=0, help_text='حداقل مبلغ سفارش برای اعمال کد')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='حداکثر تعداد استفاده (خالی = نامحدود)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='core.store')),
            ],
            options={
                'db_table': 'discount_codes',
                'unique_together': {('store', 'code')},
            },
        ),
    ]
