# Generated by Django 5.2.11 on 2026-04-11 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_discountcode'),
        ('core', '0014_store_generated_logo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('adjust', 'تنظیم موجودی'), ('transfer', 'انتقال'), ('receipt', 'رسید کالا'), ('sale', 'فروش'), ('return', 'مرجوعی')], max_length=20)),
                ('quantity_before', models.IntegerField()),
                ('quantity_change', models.IntegerField(help_text='مثبت = افزایش، منفی = کاهش')),
                ('quantity_after', models.IntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_log_entries', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='core.warehouse')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'created_at'], name='inventory_l_warehou_7d94e8_idx'), models.Index(fields=['variant', 'created_at'], name='inventory_l_variant_5a5116_idx')],
            },
        ),
    ]
