# Generated by Django 5.2.11 on 2026-04-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_inventorylog'),
        ('core', '0016_delete_contentcalendarentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=300)),
                ('caption', models.TextField(blank=True, default='')),
                ('hashtags', models.CharField(blank=True, default='', max_length=500)),
                ('suggested_time', models.CharField(blank=True, default='', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='core.store')),
            ],
            options={
                'db_table': 'content_calendar_entries',
                'ordering': ['date'],
            },
        ),
    ]
