# Generated by Django 5.2.11 on 2026-02-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_add_allow_guest_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(default='پلتفرم', max_length=100, verbose_name='حمل\u200cکننده')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('created', 'ثبت شده'), ('picked_up', 'تحویل به مرکز'), ('in_transit', 'در راه'), ('delivered', 'تحویل داده شده'), ('exception', 'مشکل')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='stores.store')),
            ],
            options={
                'verbose_name': 'ارسال',
                'verbose_name_plural': 'ارسال\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
