# Generated by Django 5.2.11 on 2026-04-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_storestaff_role_max_length'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Originating warehouse for this shipment (SO-52).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.warehouse'),
        ),
    ]
