# Generated by Django 5.2.11 on 2026-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True)),
                ('api_credentials', models.TextField(blank=True, verbose_name='API credentials (e.g. key=value)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping carrier',
                'verbose_name_plural': 'Shipping carriers',
                'ordering': ['name'],
            },
        ),
    ]
