# Generated by Django 5.2.11 on 2026-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_guest_checkout',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، مشتری باید با موبایل و OTP وارد شود.', verbose_name='خرید مهمان'),
        ),
    ]
