# Generated by Django 5.2.11 on 2026-02-12 20:39

import django.db.models.deletion
import stores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_allow_guest_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='stores/favicons/', verbose_name='فاویکون'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='لوگو'),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(blank=True, help_text='مثال: #3B82F6', max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_preset',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('minimal', 'مینیمال'), ('bold', 'پررنگ')], default='default', max_length=20, verbose_name='قالب ظاهری'),
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, validators=[stores.models.validate_domain_value], verbose_name='دامنه')),
                ('domain_type', models.CharField(choices=[('subdomain', 'زیردامنه'), ('custom', 'دامنه سفارشی')], default='custom', max_length=20)),
                ('verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('ssl_status', models.CharField(choices=[('pending', 'در انتظار'), ('active', 'فعال'), ('error', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت SSL')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='stores.store')),
            ],
            options={
                'verbose_name': 'دامنه فروشگاه',
                'verbose_name_plural': 'دامنه\u200cهای فروشگاه',
                'ordering': ['-is_primary', 'domain'],
                'unique_together': {('store', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'کارمند'), ('manager', 'مدیر')], default='staff', max_length=20, verbose_name='نقش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمند فروشگاه',
                'verbose_name_plural': 'کارمندان فروشگاه',
                'ordering': ['store', 'user'],
                'unique_together': {('store', 'user')},
            },
        ),
    ]
