# Generated by Django 5.2.11 on 2026-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='routing_plan',
            field=models.JSONField(blank=True, default=None, help_text='Auto-routing result from SmartRoutingService (SO-52).', null=True),
        ),
    ]
