# Generated by Django 5.2.11 on 2026-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_shipping_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ بازپرداخت شده'),
        ),
    ]
