# Generated by Django 5.2.11 on 2026-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_phase4_routing_plan_and_warehouse_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, help_text='Discount applied in IRR'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code_used',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
