# Generated by Django 5.2.11 on 2026-02-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_add_allow_guest_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ')),
                ('payment_details', models.TextField(blank=True, verbose_name='اطلاعات پرداخت (شبا، شماره حساب و ...)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='stores.store')),
            ],
            options={
                'verbose_name': 'درخواست تسویه',
                'verbose_name_plural': 'درخواست\u200cهای تسویه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_transactions', to='orders.order')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.payoutrequest')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stores.store')),
            ],
            options={
                'verbose_name': 'تراکنش فروشگاه',
                'verbose_name_plural': 'تراکنش\u200cهای فروشگاه',
                'ordering': ['-created_at'],
            },
        ),
    ]
