# Generated by Django 5.2.11 on 2026-02-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('orders', '0003_add_refunded_amount'),
        ('stores', '0003_domains_branding_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ کمیسیون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_commissions', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_commissions', to='stores.store')),
            ],
            options={
                'verbose_name': 'کمیسیون پلتفرم',
                'verbose_name_plural': 'کمیسیون\u200cهای پلتفرم',
                'ordering': ['-created_at'],
            },
        ),
    ]
