# Generated by Django 5.2.11 on 2026-02-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='core.store'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.store'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='payout_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.payoutrequest'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.store'),
        ),
        migrations.AddIndex(
            model_name='storetransaction',
            index=models.Index(fields=['store', 'created_at'], name='store_trans_store_i_82360f_idx'),
        ),
    ]
