# Generated by Django 5.2.11 on 2026-04-10 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0012_store_auto_route_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='مبلغ هزینه به ریال')),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('goods', 'خرید کالا'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'حمل\u200cونقل'), ('marketing', 'تبلیغات'), ('rent', 'اجاره'), ('other', 'سایر')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('is_ai_extracted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.store')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='accounting.storetransaction')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
