# Generated by Django 5.2.11 on 2026-04-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expense'),
        ('core', '0012_store_auto_route_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='گزارش متنی از AI')),
                ('suggestions', models.JSONField(default=list)),
                ('alerts', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfo_reports', to='core.store')),
            ],
            options={
                'db_table': 'cfo_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
